name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        service: [ "service1", "service2", "service-3" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ujjwal013
          password: dckr_pat_HtgA1KBsYH-ELj8Dk_lUX6RGxh0

      - name: Build Docker images (latest + version)
        run: |
          docker build -t ujjwal013/${{ matrix.service }}:latest

      - name: Push Docker images (latest + version)
        run: |
          docker push ujjwal013/${{ matrix.service }}:latest
